"""AST scanning — extract functions, methods, classes, and raw call data."""

from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path
from typing import Optional

from codegraph.filters import should_exclude
from codegraph.models import FunctionNode, RawCall

_GENERATED_FILE_PATTERNS = {
    "_pb2.py", "_pb2_grpc.py", "_pb2.pyi", "_pb2_grpc.pyi",
}

_GENERATED_DIR_PATTERNS = {
    "generated", "_generated",
}


def _is_generated_file(rel_path: str, source: str) -> bool:
    """Detect auto-generated files by filename pattern or header comment."""
    for pattern in _GENERATED_FILE_PATTERNS:
        if rel_path.endswith(pattern):
            return True

    parts = rel_path.split("/")
    for part in parts:
        if part.lower() in _GENERATED_DIR_PATTERNS:
            return True

    lines = source.split("\n", 5)[:5]
    for line in lines:
        if "generated by" in line.lower() or "auto-generated" in line.lower() or "do not edit" in line.lower():
            return True

    return False


def _extract_decorator_name(dec: ast.expr) -> str:
    if isinstance(dec, ast.Name):
        return dec.id
    if isinstance(dec, ast.Attribute):
        return dec.attr
    if isinstance(dec, ast.Call):
        return _extract_decorator_name(dec.func)
    return "unknown"


def _docstring_first_line(node: ast.AST) -> Optional[str]:
    ds = ast.get_docstring(node)
    if not ds:
        return None
    first = ds.strip().split("\n")[0]
    return first[:80] if len(first) > 80 else first


def _extract_receiver_and_name(call_node: ast.Call) -> tuple[Optional[str], Optional[str]]:
    """Return (receiver, method_name) for a call.

    Examples:
        foo()           -> (None, "foo")
        self.bar()      -> ("self", "bar")
        registry.apply()-> ("registry", "apply")
        a.b.c()         -> (None, "c")  -- deep chains, just the attr
    """
    func = call_node.func
    if isinstance(func, ast.Name):
        return None, func.id
    if isinstance(func, ast.Attribute):
        value = func.value
        if isinstance(value, ast.Name):
            return value.id, func.attr
        return None, func.attr
    return None, None


def _collect_calls(func_node: ast.AST) -> list[RawCall]:
    """Walk a function body and collect every call with receiver info."""
    raw: list[RawCall] = []
    for child in ast.walk(func_node):
        if isinstance(child, ast.Call):
            receiver, name = _extract_receiver_and_name(child)
            if name:
                raw.append(RawCall(
                    name=name,
                    receiver=receiver,
                    lineno=getattr(child, "lineno", 0),
                ))
    raw.sort(key=lambda r: r.lineno)
    seen: dict[str, int] = {}
    for r in raw:
        if r.name not in seen:
            seen[r.name] = len(seen) + 1
        r.order = seen[r.name]
    return raw


def _collect_type_assignments(func_node: ast.AST, known_classes: set[str]) -> dict[str, str]:
    """Track constructor assignments: variable -> ClassName."""
    scope: dict[str, str] = {}
    for child in ast.walk(func_node):
        if not isinstance(child, ast.Assign):
            continue
        if len(child.targets) != 1:
            continue
        target = child.targets[0]
        if not isinstance(target, ast.Name):
            continue
        value = child.value
        if isinstance(value, ast.Call):
            if isinstance(value.func, ast.Name) and value.func.id in known_classes:
                scope[target.id] = value.func.id
            elif isinstance(value.func, ast.Attribute) and value.func.attr in known_classes:
                scope[target.id] = value.func.attr
    return scope


def _detect_dynamic_dispatch(func_node: ast.AST) -> list[int]:
    """Return line numbers where getattr(obj, name) patterns occur."""
    lines: list[int] = []
    for child in ast.walk(func_node):
        if isinstance(child, ast.Call) and isinstance(child.func, ast.Name):
            if child.func.id == "getattr" and len(child.args) >= 2:
                if isinstance(child.args[1], ast.Name):
                    lines.append(getattr(child, "lineno", 0))
    return lines


class ScanResult:
    """Raw output of scanning a codebase before resolution."""
    __slots__ = (
        "nodes", "raw_calls", "type_scopes", "class_names",
        "dynamic_lines", "imports", "file_imports",
    )

    def __init__(self) -> None:
        self.nodes: list[FunctionNode] = []
        self.raw_calls: dict[str, list[RawCall]] = {}
        self.type_scopes: dict[str, dict[str, str]] = {}
        self.class_names: set[str] = set()
        self.dynamic_lines: dict[str, list[int]] = {}
        self.imports: dict[str, list[str]] = {"internal": [], "external": []}
        self.file_imports: dict[str, dict[str, str]] = {}


def scan_codebase(
    root_dir: str,
    exclude_patterns: list[str] | None = None,
) -> ScanResult:
    """Walk *root_dir*, parse every .py file, and extract graph primitives."""
    root = Path(root_dir).resolve()
    exclude = exclude_patterns or []
    result = ScanResult()

    # First pass: collect all class names so we can track constructor assignments
    for py_file in sorted(root.rglob("*.py")):
        rel_path = str(py_file.relative_to(root))
        if should_exclude(rel_path, exclude):
            continue
        try:
            source = py_file.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError, OSError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                result.class_names.add(node.name)

    # Second pass: extract functions, calls, types, imports
    for py_file in sorted(root.rglob("*.py")):
        rel_path = str(py_file.relative_to(root))
        if should_exclude(rel_path, exclude):
            continue
        try:
            source = py_file.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError, OSError):
            continue

        generated = _is_generated_file(rel_path, source)
        _visit_body(tree.body, rel_path, None, result, is_generated=generated)
        _collect_file_imports(tree, result)
        _collect_per_file_imports(tree, rel_path, result)

    result.imports["internal"] = sorted(set(result.imports["internal"]))
    result.imports["external"] = sorted(set(result.imports["external"]))
    return result


def _visit_body(
    body: list[ast.stmt],
    rel_path: str,
    class_name: Optional[str],
    result: ScanResult,
    is_generated: bool = False,
) -> None:
    for stmt in body:
        if isinstance(stmt, ast.ClassDef):
            result.class_names.add(stmt.name)
            _visit_body(stmt.body, rel_path, class_name=stmt.name, result=result, is_generated=is_generated)
        elif isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            node = _make_node(stmt, rel_path, class_name, is_generated=is_generated)
            result.nodes.append(node)

            calls = _collect_calls(stmt)
            result.raw_calls[node.id] = calls

            type_scope = _collect_type_assignments(stmt, result.class_names)
            if type_scope:
                result.type_scopes[node.id] = type_scope

            dyn = _detect_dynamic_dispatch(stmt)
            if dyn:
                result.dynamic_lines[node.id] = dyn


def _make_node(
    func_node: ast.FunctionDef | ast.AsyncFunctionDef,
    rel_path: str,
    class_name: Optional[str],
    is_generated: bool = False,
) -> FunctionNode:
    if class_name:
        node_id = f"{rel_path}:{class_name}.{func_node.name}"
        short = f"{class_name}.{func_node.name}"
        ntype = "method"
    else:
        node_id = f"{rel_path}:{func_node.name}"
        short = func_node.name
        ntype = "function"

    end = getattr(func_node, "end_lineno", func_node.lineno)
    return FunctionNode(
        id=node_id,
        file=rel_path,
        class_name=class_name,
        function=func_node.name,
        short_name=short,
        lineno=func_node.lineno,
        end_lineno=end,
        params=len(func_node.args.args),
        lines=end - func_node.lineno,
        docstring=_docstring_first_line(func_node),
        is_async=isinstance(func_node, ast.AsyncFunctionDef),
        decorators=[_extract_decorator_name(d) for d in func_node.decorator_list],
        node_type=ntype,
        is_generated=is_generated,
    )


def _collect_per_file_imports(tree: ast.Module, rel_path: str, result: ScanResult) -> None:
    """Track which names each file imports, for resolver disambiguation."""
    mapping: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                local_name = alias.asname if alias.asname else alias.name
                mapping[local_name] = node.module
        elif isinstance(node, ast.Import):
            for alias in node.names:
                local_name = alias.asname if alias.asname else alias.name
                mapping[local_name] = alias.name
    if mapping:
        result.file_imports[rel_path] = mapping


def _collect_file_imports(tree: ast.Module, result: ScanResult) -> None:
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                pkg = alias.name.split(".")[0]
                if pkg == "feast":
                    result.imports["internal"].append(alias.name)
                else:
                    result.imports["external"].append(pkg)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                pkg = node.module.split(".")[0]
                if pkg == "feast":
                    result.imports["internal"].append(node.module)
                else:
                    result.imports["external"].append(pkg)
